<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?=App::config('nameApp');?></title>
<link rel="stylesheet" href="<?=App::config('url')?>public/css/bootstrap.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<?php if(isset($css)): ?>
    <link rel="stylesheet" href="<?=App::config('url')?>public/css/<?=$css?>">
<?php endif; ?>
<?php /* https://css-tricks.com/essential-meta-tags-social-media/ */?>
<!--  Essential META Tags -->
<meta property="og:title" content="<?=App::config('nameApp');?>">
<meta property="og:type" content="article" />
<meta property="og:image" content="<?=App::config('url')?>public/img/thumbnail.jpg">
<meta property="og:url" content="<?=App::config('url')?>">
<meta name="twitter:card" content="summary_large_image">

<!--  Non-Essential, But Recommended -->
<meta property="og:description" content="<?=App::config('nameApp');?>">
<meta property="og:site_name" content="<?=App::config('nameApp');?>">
<meta name="twitter:image:alt" content="<?=App::config('nameApp');?>">